apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: krm_template_fullstack_typesript
build:
  artifacts:
    - image: anthonycorletti/krm-template-fullstack-typescript-api
      docker:
        dockerfile: api/Dockerfile
    - image: anthonycorletti/krm-template-fullstack-typescript-ui
      docker:
        dockerfile: ui/Dockerfile
deploy:
  kustomize:
    paths:
      - overlays/development
profiles:
  - name: prod
    deploy:
      kustomize:
        paths:
          - overlays/production
