---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    spec:
      containers:
        - name: api
          image: anthonycorletti/krm-template-fullstack-typescript-api:v0.0.1
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    spec:
      containers:
        - name: ui
          image: anthonycorletti/krm-template-fullstack-typescript-ui:v0.0.1
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
