---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: anthonycorletti/krm-template-fullstack-typescript-api:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: api
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8000
      targetPort: 8000
