name: publish

on:
  release:
    types:
      - created

env:
  API_IMAGE_NAME: "gcr.io/krm-template-testing/api"
  UI_IMAGE_NAME: "gcr.io/krm-template-testing/ui"
  GKE_CLUSTER_NAME: autopilot-cluster-1 # TODO: replace with your cluster name
  GKE_REGION: us-central1 # TODO: replace with your cluster region

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: update ubuntu
        run: sudo apt-get update -y

      - id: gcp_auth
        name: authenticate to gcp
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_ID_PROD }}/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "${{ secrets.GCP_SA_PROD }}"

      - name: Set up docker to communicate via gcloud cli
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          gcloud auth login --brief --cred-file="${{ steps.gcp_auth.outputs.credentials_file_path }}"
          gcloud auth configure-docker

      - name: skaffold build and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          skaffold build --cache-artifacts=false

      - name: skaffold deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_REGION
          skaffold deploy --images=$API_IMAGE_NAME --images=$UI_IMAGE_NAME
