name: test-api

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
      - ".github/workflows/test-api.yaml"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "api/**"
      - ".github/workflows/test-api.yaml"

env:
  API_IMAGE_NAME: gcr.io/krm-template-testing/api # TODO: replace with your image name
  GKE_CLUSTER_NAME: autopilot-cluster-1 # TODO: replace with your cluster name
  GKE_REGION: us-central1 # TODO: replace with your cluster region

jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
      fail-fast: false

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: apt-get update
        run: |
          sudo apt-get update -y \
          && sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg \
            lsb-release \
            software-properties-common \
          && curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 \
          && sudo install skaffold /usr/local/bin/ \
          && curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        working-directory: api
        run: ./scripts/install.sh

      - name: run tests
        working-directory: api
        run: ./scripts/test.sh

      - name: skaffold build container
        if: github.event_name == 'pull_request'
        run: skaffold build --push=false --cache-artifacts=false --build-image=$API_IMAGE_NAME

      - id: gcp_auth
        name: authenticate to gcp
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_ID_DEV }}/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "${{ secrets.GCP_SA_DEV }}"

      - name: Set up docker to communicate via gcloud cli
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          gcloud auth login --brief --cred-file="${{ steps.gcp_auth.outputs.credentials_file_path }}"
          gcloud auth configure-docker

      - name: skaffold build and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          skaffold build --cache-artifacts=false --build-image=$API_IMAGE_NAME

      - name: skaffold deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $GKE_REGION
          skaffold deploy --images=$API_IMAGE_NAME
